image: node:latest

cache:
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
  artifacts:
    paths: 
        - dist

publish:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
